import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import ExerciseProvider from "@/context/ExerciseContext";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/shared/Footer";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitLog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <ExerciseProvider>
        <Navbar />
        {children}

        <Footer />

        </ExerciseProvider>

        <ToastContainer
          position="top-right"
          autoClose={2000}
        />
        </body>
    </html>
  );
}
